// This file was generated by the XState CLI, please do not edit it manually.
import { assign, createMachine } from 'xstate';

const machine = createMachine(
  {
    id: 'player-machine',
    initial: 'loggedOut',
    states: {
      loggedOut: {
        on: {
          'LOG-IN': {
            target: 'loggedIn',
            actions: assign({ username: ({ event }) => event.username }),
          },
        },
      },
      loggedIn: {
        on: {
          'SELECT-PLAYER': {
            target: 'loggedIn',
            actions: assign({ selectedPlayer: ({ event }) => event.player }),
          },
        },
      },
    },
    types: {
      events: {} as
        | { type: 'LOG-IN'; username: string }
        | { type: 'SELECT-PLAYER'; player: string },
      context: {} as { username: string; selectedPlayer: string },
    },
  },
  {
    actions: {},
    actors: {},
    guards: {},
    delays: {},
  },
);
export const skyConfig = {
  actorId: '843d0cab-ace9-4975-8c0f-badbe9d42528',
  machine,
};
